color0 #47464f
color1 #ffb4ab
color2 #c5c0ff
color3 #c7c4dc
color4 #ebb9d0
color5 #c5c0ff
color6 #c7c4dc
color7 #e5e1e9
color8 #928f99
color9 #ffb4ab
color10 #c5c0ff
color11 #c7c4dc
color12 #ebb9d0
color13 #c5c0ff
color14 #c7c4dc
color15 #e5e1e9

cursor                #e5e1e9
cursor_text_color     #131318
background            #131318
foreground            #e5e1e9
selection_foreground  #c8c5d0
selection_background  #47464f
active_border_color   #c5c0ff
inactive_border_color #47464f
url_color             #c5c0ff

active_tab_foreground   #2d2960
active_tab_background   #c5c0ff
inactive_tab_foreground #c8c5d0
inactive_tab_background #47464f
cursor_trail_color      #c8c5d0
