[colors]
ansi = [
    "#141315",
    "#ffb4ab",
    "#eabac4",
    "#cec3d0",
    "#d4bfdd",
    "#eabac4",
    "#cec3d0",
    "#e7e1e3",
]
background = "#141315"
brights = [
    "#968e96",
    "#ffb4ab",
    "#eabac4",
    "#cec3d0",
    "#d4bfdd",
    "#eabac4",
    "#cec3d0",
    "#e7e1e3",
]
cursor_bg = "#e7e1e3"
cursor_border = "#e7e1e3"
cursor_fg = "#141315"
foreground = "#e7e1e3"
selection_bg = "#4a454c"
selection_fg = "#ccc4cc"

[metadata]
name = "Noctalia"
