[colors]
ansi = [
    "#141314",
    "#ffb4ab",
    "#dcbece",
    "#c8c5cf",
    "#c6c4db",
    "#dcbece",
    "#c8c5cf",
    "#e5e1e3",
]
background = "#141314"
brights = [
    "#929097",
    "#ffb4ab",
    "#dcbece",
    "#c8c5cf",
    "#c6c4db",
    "#dcbece",
    "#c8c5cf",
    "#e5e1e3",
]
cursor_bg = "#e5e1e3"
cursor_border = "#e5e1e3"
cursor_fg = "#141314"
foreground = "#e5e1e3"
selection_bg = "#47464c"
selection_fg = "#c8c5cd"

[metadata]
name = "Noctalia"
