$mainMod = SUPER # Sets "Windows" key as main modifier
$terminal = wezterm
$fileManager = nautilus
$browser = zen

$menu = noctalia-shell ipc call launcher toggle 
$clipboard = noctalia-shell ipc call launcher clipboard
$session = noctalia-shell ipc call sessionMenu toggle

$volumeUp = noctalia-shell ipc call volume increase
$volumeDown = noctalia-shell ipc call volume decrease
$volumeMute = noctalia-shell ipc call volume muteOutput

$inputMute = noctalia-shell ipc call volume muteInput

$brightnessUp = noctalia-shell ipc call brightness increase
$brightnessDown = noctalia-shell ipc call brightness decrease

$wallpaperSelector = noctalia-shell ipc call wallpaper toggle
$wallpaperRandom = noctalia-shell ipc call wallpaper random

$toggleMusic = noctalia-shell ipc call media playPause

$cursorTheme = Bibata-Modern-Ice
$cursorSize = 24
